### Тема “Вычисления с помощью Numpy”

### Задание 1

In [9]:
import numpy as np

In [10]:
a  = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a = a.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [11]:
print("Средние значения столбцов: {}".format(a.mean(axis=0)))

Средние значения столбцов: [2.  8.4]


### Задание 2

In [17]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [38]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [39]:
N = a.shape[0]
N

5

In [36]:
cov = a_centered_sp/(N -1)
print(f'Коварианция равна {cov}')

Коварианция равна 2.0


### Задание 4**

In [40]:
cov2 = np.cov(a.T)
cov2

array([[1. , 2. ],
       [2. , 4.3]])

In [42]:
cov == cov2[0, 1]

True

### Тема “Работа с данными в Pandas”

### Задание 1

In [49]:
import pandas as pd

In [147]:
a = { "author_id": [1, 2, 3],
     "author_name": ['Тургенев', 'Чехов', 'Островский']}
authors = pd.DataFrame(a)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [148]:
b = {"author_id": [1, 1, 1, 2, 2, 3, 3],
     "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
     "price": [450, 300, 350, 500, 450, 370, 290]}
book = pd.DataFrame(b)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

In [149]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

In [150]:
top5 = pd.DataFrame(authors_price.nlargest(5, "price"))
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

In [151]:
table = authors_price.loc[ :, ["author_name", "price"]]
table

author_name  price
0    Тургенев    450
1    Тургенев    300
2    Тургенев    350
3       Чехов    500
4       Чехов    450
5  Островский    370
6  Островский    290

In [152]:
authors_stat = table.groupby("author_name")

a = { "min_price": authors_stat["price"].min(), 
    "max_price": authors_stat["price"].max(),
    "mean_price": authors_stat["price"].mean()} 
b = pd.DataFrame(a)

b

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

### Задание 5**

In [153]:
authors_price.loc[authors_price["author_name"].notnull(), "cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [121]:
?pd.pivot_table

In [154]:
book_info = pd.pivot_table(authors_price, values="price", index="author_name", columns=["cover"], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [155]:
book_info.to_pickle("book_info.pkl") 

In [156]:
book_info2 = pd.read_pickle("book_info.pkl")
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950